# Generated by Django 4.0.5 on 2022-06-16 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_of_car', models.CharField(max_length=50)),
                ('model_of_car', models.CharField(max_length=50)),
                ('content', models.TextField(blank=True)),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('date_create', models.CharField(max_length=10)),
            ],
        ),
    ]
